### ISSUE TITLE
Can't install in Redmine 2.6 - cannot specify same gem twice

### ISSUE THREAD

**Issue by yozart** [abahgat/redmine_didyoumean#67]
While executing the migrate command, I got the below error message.

You cannot specify the same gem twice with different version requirements.
You specified: mysql2 (=0.3.11) and mysql2 (~) 0.3.11)

I used the latest version available (from 4 days ago). My redmine is bitnami redmine 2.6

![2015-01-03_23-13-14](https://cloud.githubusercontent.com/assets/3858273/5603958/77b70608-939e-11e4-85c6-1fd3d6d1ceca.png)

**Comment by maiklindner** [comment]
you could comment out the line in plugins/redmine_didyoumean/Gemfile

**Comment by jeick** [comment]
This results in the following when installing on Redmine 2.6.1 on Windows without Sphinx.

C:\Bitnami\redmine-2.6.1-0\apps\redmine\htdocs>ruby bin/rake redmine:plugins RAI
LS_ENV="production"
rake aborted!
NameError: uninitialized constant ThinkingSphinx
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/plugins/redmine_didyoumean/app/in
dices/issue_index.rb:2:in `<top (required)>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/plugins/redmine_didyoumean/init.r
b:4:in `require_relative'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/plugins/redmine_didyoumean/init.r
b:4:in `<top (required)>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in `blo
ck in load'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `eac
h'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `loa
d'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/config/initializers/30-redmine.rb
:19:in `<top (required)>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/engine.rb:592:in `each'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/initializable.rb:30:in `run'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/initializable.rb:54:in `each'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/application.rb:136:in `initialize!'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rai
lties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tas
ks'
C:/Bitnami/redmine-2.6.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in `blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by dominch** [comment]
type bundle install

**Comment by yozart** [comment]
Well, I have some proxy issues for the time being. I can't do any bundle install ! If anyone managed to get it working behind a firewall, I'd be glad to get some help. I saw dozens of topics on this subject but none of them helped. I guess issue  is coming from the proxy

**Comment by dominch** [comment]
I'm behind firewall too, and it's not working without setting system variables:
<pre>
export http_proxy=http://proxy01.company.net:3128
export https_proxy=http://proxy01.company.net:3128
</pre>
That works for bash + linux, You may have different settings and different proxy access control.

**Comment by yozart** [comment]
Hello thanks for the answer but already tried it. Unfortunately didn't worked for me. I also tried to define those in Environment settings (I'm on Windows Server using Bitnami installer). 

As I said, I guess it's more related to some configuration issues on the proxy or firewall. I need to see with my network team. Thanks anyway. I'll tell you up to date once I got a solution

**Comment by korin** [comment]
I see few solutions for proxy problems
1. you can set it in ~/.gemrc (I think ~ is $HOME) eg:
    ```
    ---
    install: --http-proxy=http://USERNAME:PASSWORD@ADDRESS:PORT
    ```
    see [rubygems command reference](http://guides.rubygems.org/command-reference/)
2. set transparent socks proxy, I never tried it on windows
3. use proxy wrapper eg. proxychains or proxytunnel
4. [package gems](http://bundler.io/v1.2/bundle_package.html) on other platform, copy to windows and instal  with [--local flag](http://bundler.io/v1.2/bundle_install.html) 

FYI environment can be set in Gemfile, on top of the file write `ENV['http_proxy'] = 'user:pass@proxy:port'`

**Comment by yozart** [comment]
Thanks for those information. I finally went with solution "Package gems on another platform and install them using --local flag
I was failing to set proxy configuration and Proxy team was not very cooperative to help ;)
