### ISSUE TITLE
Port to Redmine 3.0

### ISSUE THREAD

**Issue by dalemarchand** [abahgat/redmine_didyoumean#72]
Would like be able to use this plugin with a Redmine 3.0 installation.

**Comment by Androc** [comment]
Did you try ? What was the error ?

**Comment by dalemarchand** [comment]
Our sysadmin tried it and said it failed.  Let me try to get the errors from him and I'll post them.

**Comment by Androc** [comment]
Would be great because "it does not work" does not help at all :)

**Comment by dalemarchand** [comment]
Sorry.  I (should) know better.

**Comment by Androc** [comment]
Don't worry, it is not always easy to report a but if it is not you who found it.

**Comment by dalemarchand** [comment]
Oh, its definitely easy to report a bug you don't find yourself.  I get those all the time.

Its just not easy to do it *well*.

**Comment by Androc** [comment]
That is what I meant ;)

**Comment by dalemarchand** [comment]
Here's our Redmine installation:
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  no plugin installed

When we run:

rake redmine:plugins:migrate NAME=redmine_didyoumean VERSION=0 RAILS_ENV=production

We get this error output:

An error occurred while loading the routes definition of redmine_didyoumean plugin (/home/redmine/redmine-3.0.3/plugins/redmine_didyoumean/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".

**Comment by Androc** [comment]
Ok. Thanks. I will have a look tomorrow to the code, if I can help.

**Comment by dalemarchand** [comment]
Thanks but in true crappy bug reporting fashion. my admin now reports that he was able to get it working once we tried the current source (instead of the 1.2.0 version from 2012) and he loaded a couple of gems he was missing.  Sorry to waste your time.

**Comment by Androc** [comment]
Good news :)
