### ISSUE TITLE
Redmine 3.x

### ISSUE THREAD

**Issue by Angelinsky7** [abahgat/redmine_didyoumean#73]
Hi,

I would like to know if you plan to port your awesome plugin to redmine 3.x ?

Thanks

**Comment by Androc** [comment]
Hello,

I am not the developer but did you try to install it on redmine 3? What was the error?

**Comment by Angelinsky7** [comment]
Hi,
for the plugin to work "correctly" with the sql search (only the only_open_condition tested for now) with ruby 4....

Change the file

  redmine_didyoumean/lib/redmine_didyoumean/searching_by_sql.rb

And change the line 33: (the all method dont take params anymore)

#valid_statuses = IssueStatus.all(:conditions => ["is_closed <> ?", true]).collect(&:id)
valid_statuses = IssueStatus.where("is_closed <> ?", true).collect(&:id)

**Comment by Androc** [comment]
Nice to ear, good job.
Why do you put "correctly" in quotes ?
Is there something that still does not work after your correction ?

**Comment by Angelinsky7** [comment]
For what i've tested everything is working fine.
but... i've only tested my settings and the way we like this plugin to behave.

So that's why i put "correctly" like that, i'm not sure that it's working for all settings.... (maybe there is other part of the code that use obsolete code.

**Comment by Androc** [comment]
Ok. Thanks for your feedback. As "didyoumean" seems pretty simple, I think your working case is pretty well the working case of everybody so I suppose your can say that your issue can be safely closed.

**Comment by Angelinsky7** [comment]
I agree... but isn't it something that some other people could want ?

**Comment by Androc** [comment]
Oh yes, sorry forget something :)
I should have written : "make a pull request to make your solution available for all".

**Comment by Angelinsky7** [comment]
... no it's me kind of new into git.
Thanks for all your help and support

**Comment by Androc** [comment]
No problem. Do you know how to make a pull request ? Do you need help ?
