### ISSUE TITLE
Whether Can support　Redmine3.X

### ISSUE THREAD

**Issue by codyliou** [abahgat/redmine_didyoumean#78]
An error occurred while loading the routes definition of redmine_didyoumean plugin (C:/Sites/redmine-3.1.0/plugins/redmine_didyoumean/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".

**Comment by abahgat** [comment]
Is this still occurring with the current `HEAD` version?

`match` has already been changed to `get` [here](https://github.com/abahgat/redmine_didyoumean/commit/90e54fa8cb55242caa11112cb05a9640352b9eed#diff-21497849d8f00507c9c8dcaf6288b136), so updating to the latest version of the code should make this issue go away.

**Comment by archonwang** [comment]
it supports with 3.2.X. at present I still used it . Thanks @abahgat .

**Comment by abahgat** [comment]
Thanks for checking!
