### ISSUE TITLE
Dependency issue with Redmine 3.2.3

### ISSUE THREAD

**Issue by col-panic** [abahgat/redmine_didyoumean#81]
When installing with redmine 3.2.3 i get the following error

```
You have requested:
  rake ~> 10.1.1

The bundle currently has rake locked at 11.2.2.
Try running `bundle update rake`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
```

**Comment by rbugajewski** [comment]
Try to run `bundle update rake` inside your Redmine directory as the message suggests.

**Comment by samapico** [comment]
For Redmine 3.4.3, I had to change the version numbers directly in the Gemfile to make it work. I changed rake from 10.1.1 to 12.2.1, and mysql2 from 0.3.11 to 0.4.6.

**Comment by col-panic** [comment]
Nice! I just adapted Gemfile to fit for the version requested by 3.2.3 and it works without any problem :)
